---
apiVersion: v1
kind: Service
metadata:
  name: necbaas-api-server
spec:
  type: LoadBalancer
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: necbaas-api-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: necbaas-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: necbaas-api-server
  template:
    metadata:
      labels:
        app: necbaas-api-server
    spec:
      containers:
      - name: api-container
        image: necbaas/api-server
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: necbaas-baas-server-config
        - secretRef:
            name: necbaas-mongo-secrets
#         # volumeMounts の追記
#         volumeMounts:
#           - mountPath: "/data/db"
#             name: mongo-data
#       # volumes の追記
#       volumes:
#         - name: mongo-data
#           persistentVolumeClaim:
#             claimName: necbaas-nfs-claim
