---
apiVersion: v1
kind: Service
metadata:
  name: necbaas-api-console-server
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: necbaas-api-console-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: necbaas-api-console-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: necbaas-api-console-server
  template:
    metadata:
      labels:
        app: necbaas-api-console-server
    spec:
      containers:
        - name: api-console-container
          image: necbaas/api-console-server
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: necbaas-baas-server-config
          - secretRef:
              name: necbaas-mongo-secrets
        - name: fluentd-container
          image: necbaas/baas-fluentd
          ports:
            - containerPort: 24224
          envFrom:
          - configMapRef:
              name: necbaas-fluentd-config
          - secretRef:
              name: necbaas-mongo-secrets
#         # volumeMounts の追記
#         volumeMounts: 
#           - mountPath: "/data/db"
#             name: mongo-data
#       # volumes の追記
#       volumes:
#         - name: mongo-data
#           persistentVolumeClaim:
#             claimName: necbaas-nfs-claim

