---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: necbaas-cloudfn-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: necbaas-cloudfn-server
  template:
    metadata:
      labels:
        app: necbaas-cloudfn-server
    spec:
      containers:
      - name: fluentd-container
        image: necbaas/baas-fluentd
        ports:
        - containerPort: 24224
        envFrom:
        - configMapRef:
            name: necbaas-fluentd-config
        - secretRef:
            name: necbaas-mongo-secrets
      - name: cloudfn-container
        image: necbaas/cloudfn-server
        envFrom:
        - configMapRef:
            name: necbaas-cloudfn-server-config
