---
apiVersion: v1
kind: Service
metadata:
  name: necbaas-mongodb-server
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 27017
      targetPort: 27017
  selector:
    app: necbaas-mongodb-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: necbaas-mongodb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: necbaas-mongodb-server
  template:
    metadata:
      labels:
        app: necbaas-mongodb-server
    spec:
      containers:
        - name: mongodb-container
          image: mongo:4
          ports:
            - containerPort: 27017
          env:
            - name: "MONGO_INITDB_ROOT_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: necbaas-mongo-secrets
                  key: MONGO_USERNAME
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: necbaas-mongo-secrets
                  key: MONGO_PASSWORD

