---
apiVersion: v1
kind: Secret
metadata:
  name: necbaas-rabbitmq-secrets
type: Opaque
data:
  # Encoded by base64
  # Used by  rabbitmq-server
  RABBITMQ_DEFAULT_USER: "cmFiYml0bXE="
  RABBITMQ_DEFAULT_PASS: "cmFiYml0bXE="

---
apiVersion: v1
kind: Service
metadata:
  name: necbaas-rabbitmq-server
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 5672
      targetPort: 5672
  selector:
    app: necbaas-rabbitmq-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: necbaas-rabbitmq-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: necbaas-rabbitmq-server
  template:
    metadata:
      labels:
        app: necbaas-rabbitmq-server
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq:3-alpine
          ports:
            - containerPort: 5672
          envFrom:
          - secretRef:
              name: necbaas-rabbitmq-secrets

